version: '3'
services:
    # Server
    java:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: java
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        volumes:
            - ./server/tmp:/tmp
        expose: 
            - 8080
        depends_on:
            - mysql
    #Frontend
    nginx:
        image: nginx:1.13.8
        container_name: nginx
        volumes:
            - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./client/react/build:/var/www/html
        ports:
            - 80:80
        links:
            - react
            - java
    react:
        build:
            context: ./client/react
            dockerfile: Dockerfile
        container_name: react
        environment:
            - REACT_APP_BASE_URL=http://localhost
            - REACT_APP_API_URL=http://localhost
            - REACT_APP_API_PATH=/api
        volumes:
            - ./client/react/build:/app/build
    # Database
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_DATABASE=shortener
            - MYSQL_USER=shortener
            - MYSQL_PASSWORD=shortenerpassword
        volumes:
            - ./database/data:/var/lib/mysql
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        expose:
             - 3306
        ports:
            - 3306:3306
    #Database web interface
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        ports:
#            - 8080:80
#        links:
#            - mysql
#        environment:
#            - MYSQL_USERNAME=root
#            - MYSQL_ROOT_PASSWORD=rootpassword
#            - PMA_ARBITRARY=1
#        restart: always
#        volumes:
#         - /sessions

